createOrReplace

	model Model
		culture: en-US
		defaultPowerBIDataSourceVersion: powerBI_V3
		sourceQueryCulture: en-US
		dataAccessOptions
			legacyRedirects
			returnErrorValuesAsNull

		table Fact_OngoingWaits
			lineageTag: c669cbde-fdb4-4a20-92cf-b35d9e6e3ff2

			measure 'Patients Waiting' =
					
					VAR LatestPeriod =
					    CALCULATE (
					        MAX ( Fact_OngoingWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR BoardSelected =
					    ISFILTERED ( Dim_HealthBoard[HealthBoardCode] )
					        || ISFILTERED ( Dim_HealthBoard[Board Name] )
					        || ISFILTERED ( Dim_HealthBoard[Board Type] )
					VAR SpecialtySelected = ISFILTERED ( Dim_Specialty[SpecialtyCode] ) || ISFILTERED ( Dim_Specialty[Specialty Name] )
					VAR ScopeRows =
					    CALCULATETABLE (
					        Fact_OngoingWaits,
					        Fact_OngoingWaits[PeriodEndDate] = LatestPeriod,
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_OngoingWaits[HealthBoardCode] ),
					                IF (
					                    BoardSelected,
					                    Fact_OngoingWaits[HealthBoardCode] <> "S92000003",
					                    Fact_OngoingWaits[HealthBoardCode] = "S92000003"
					                )
					            )
					        ),
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_OngoingWaits[SpecialtyCode] ),
					                IF (
					                    SpecialtySelected,
					                    Fact_OngoingWaits[SpecialtyCode] <> "Z9",
					                    Fact_OngoingWaits[SpecialtyCode] = "Z9"
					                )
					            )
					        )
					    )
					VAR HasSuppressed =
					    NOT ISEMPTY ( FILTER ( ScopeRows, ISBLANK ( Fact_OngoingWaits[NumberWaiting] ) ) )
					RETURN
					    IF ( NOT HasSuppressed, SUMX ( ScopeRows, Fact_OngoingWaits[NumberWaiting] ) )
				formatString: 0
				lineageTag: 2cbaa34b-cdbf-42a0-b523-b6cdb8da559e

			measure '% Waiting Over 12 Weeks' =
					
					DIVIDE ( [Waiting Over 12 Weeks], [Patients Waiting] )
				formatString: 0.0%;-0.0%;0.0%
				lineageTag: c5d0c8f8-d0a1-4c3e-bf34-b06c1f4a8da1

			measure 'Waiting Over 12 Weeks' =
					
					VAR LatestPeriod =
					    CALCULATE (
					        MAX ( Fact_OngoingWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR BoardSelected =
					    ISFILTERED ( Dim_HealthBoard[HealthBoardCode] )
					        || ISFILTERED ( Dim_HealthBoard[Board Name] )
					        || ISFILTERED ( Dim_HealthBoard[Board Type] )
					VAR SpecialtySelected = ISFILTERED ( Dim_Specialty[SpecialtyCode] ) || ISFILTERED ( Dim_Specialty[Specialty Name] )
					VAR ScopeRows =
					    CALCULATETABLE (
					        Fact_OngoingWaits,
					        Fact_OngoingWaits[PeriodEndDate] = LatestPeriod,
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_OngoingWaits[HealthBoardCode] ),
					                IF (
					                    BoardSelected,
					                    Fact_OngoingWaits[HealthBoardCode] <> "S92000003",
					                    Fact_OngoingWaits[HealthBoardCode] = "S92000003"
					                )
					            )
					        ),
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_OngoingWaits[SpecialtyCode] ),
					                IF (
					                    SpecialtySelected,
					                    Fact_OngoingWaits[SpecialtyCode] <> "Z9",
					                    Fact_OngoingWaits[SpecialtyCode] = "Z9"
					                )
					            )
					        )
					    )
					VAR HasSuppressed =
					    NOT ISEMPTY ( FILTER ( ScopeRows, ISBLANK ( Fact_OngoingWaits[NumberOver12Weeks] ) ) )
					RETURN
					    IF ( NOT HasSuppressed, SUMX ( ScopeRows, Fact_OngoingWaits[NumberOver12Weeks] ) )
				formatString: 0
				lineageTag: 73e7af62-ba57-45ef-bc99-3ff478d395a2

			measure '% Waiting Over 12 Weeks (Scotland)' =
					
					CALCULATE (
					    [% Waiting Over 12 Weeks],
					    REMOVEFILTERS ( Dim_HealthBoard )
					)
				formatString: 0.0%;-0.0%;0.0%
				displayFolder: Benchmark
				lineageTag: 222d587f-5552-4b24-8854-660b7e15b628

			measure '% Over 12 Weeks vs Scotland' =
					
					VAR BoardValue = [% Waiting Over 12 Weeks]
					VAR ScotlandValue = [% Waiting Over 12 Weeks (Scotland)]
					RETURN
					    IF (
					        NOT ISBLANK ( BoardValue ) && NOT ISBLANK ( ScotlandValue ),
					        BoardValue - ScotlandValue
					    )
				formatString: +0.0%;-0.0%;0.0%
				displayFolder: Benchmark
				lineageTag: 42148c3a-e89b-4457-b107-d04ba20c269e

				annotation PBI_FormatHint = {"isCustom":true}

			measure '% Waiting Over 12 Weeks (12M Ago)' =
					
					VAR CurrentPeriod =
					    CALCULATE (
					        MAX ( Fact_OngoingWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR PriorPeriod = EOMONTH ( CurrentPeriod, -12 )
					RETURN
					    CALCULATE (
					        [% Waiting Over 12 Weeks],
					        REMOVEFILTERS ( Dim_Period ),
					        Dim_Period[PeriodEndDate] = PriorPeriod
					    )
				formatString: 0.0%;-0.0%;0.0%
				displayFolder: Benchmark
				lineageTag: a7d86fcb-75f0-4771-bb85-b9ddd98508d0

			measure '% Over 12 Weeks Change vs 12M Ago' =
					
					VAR CurrentValue = [% Waiting Over 12 Weeks]
					VAR PriorValue = [% Waiting Over 12 Weeks (12M Ago)]
					RETURN
					    IF (
					        NOT ISBLANK ( CurrentValue ) && NOT ISBLANK ( PriorValue ),
					        CurrentValue - PriorValue
					    )
				formatString: +0.0%;-0.0%;0.0%
				displayFolder: Benchmark
				lineageTag: aa553f10-04f0-473f-9c58-317d0e119189

				annotation PBI_FormatHint = {"isCustom":true}

			measure 'Patients Waiting (12M Ago)' =
					
					VAR CurrentPeriod =
					    CALCULATE (
					        MAX ( Fact_OngoingWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR PriorPeriod = EOMONTH ( CurrentPeriod, -12 )
					RETURN
					    CALCULATE (
					        [Patients Waiting],
					        REMOVEFILTERS ( Dim_Period ),
					        Dim_Period[PeriodEndDate] = PriorPeriod
					    )
				displayFolder: Benchmark
				lineageTag: 8c414ade-358e-49aa-9b83-a3e96746c698

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Patients Waiting Change vs 12M Ago' =
					
					DIVIDE (
					    [Patients Waiting] - [Patients Waiting (12M Ago)],
					    [Patients Waiting (12M Ago)]
					)
				formatString: " +0.0%;-0.0%;0.0%"
				displayFolder: Benchmark
				lineageTag: 53947a5d-b96b-4aec-b18d-8fc5814c6b99

				annotation PBI_FormatHint = {"isCustom":true}

			measure 'Deep Dive Title' =
					
					VAR SelectedBoard = SELECTEDVALUE ( Dim_HealthBoard[Board Name] )
					RETURN
					    IF (
					        ISBLANK ( SelectedBoard ),
					        "Health Board Deep Dive — drill through from a board on the Overview or Activity pages",
					        SelectedBoard & " — Health Board Deep Dive"
					    )
				displayFolder: Benchmark
				lineageTag: 9c71cf00-7a9c-4ae9-b564-48bafc2944a6

			measure 'Special Board Note' =
					
					IF (
					    SELECTEDVALUE ( Dim_HealthBoard[Board Type] ) = "Special",
					    "Note: The Golden Jubilee National Hospital is a national referral centre. Its case mix differs from regional boards, so comparisons with the Scotland average should be interpreted with caution.",
					    ""
					)
				lineageTag: fce85cfc-c0fb-422c-9faf-0fd731d7984b

			measure 'Patients Waiting (Pre-COVID)' = ```
					
					CALCULATE (
					    [Patients Waiting],
					    Dim_Period[PeriodEndDate] = DATE ( 2020, 2, 29 )
					)
					
					```
				formatString: 0
				displayFolder: Benchmark
				lineageTag: 1f572b4e-a8c8-41bc-aa49-20c1f5642819

			measure 'Patients Waiting vs Pre-COVID %' =
					
					VAR CurrentWaiting = [Patients Waiting]
					VAR Baseline = [Patients Waiting (Pre-COVID)]
					RETURN
					    IF (
					        NOT ISBLANK ( CurrentWaiting ) && NOT ISBLANK ( Baseline ),
					        DIVIDE ( CurrentWaiting - Baseline, Baseline )
					    )
				formatString: +0.0%;-0.0%;0.0%
				displayFolder: Benchmark
				lineageTag: a5f86a4d-0e33-4aeb-88a7-e94d8ff5d621

				annotation PBI_FormatHint = {"isCustom":true}

			column HealthBoardCode
				dataType: string
				isHidden
				lineageTag: 8680db3a-b243-45c2-94f8-5d1150ee13c6
				summarizeBy: none
				sourceColumn: HealthBoardCode

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column HBTQF
				dataType: string
				lineageTag: 3df81189-35f8-4710-949d-2b574da07cf5
				summarizeBy: none
				sourceColumn: HBTQF

				annotation SummarizationSetBy = Automatic

			column PatientType
				dataType: string
				isHidden
				lineageTag: 6e723c42-2284-4070-a69d-f64bdf5bb85b
				summarizeBy: none
				sourceColumn: PatientType

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SpecialtyCode
				dataType: string
				isHidden
				lineageTag: c7f544e2-8036-441e-8ff9-b285bbcb8758
				summarizeBy: none
				sourceColumn: SpecialtyCode

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SpecialtyQF
				dataType: string
				lineageTag: 20922a17-3c5a-4d15-aace-0ff7583baff8
				summarizeBy: none
				sourceColumn: SpecialtyQF

				annotation SummarizationSetBy = Automatic

			column NumberWaiting
				dataType: int64
				formatString: 0
				lineageTag: 6684c97b-9d55-40c7-b489-d7fe7ab6e469
				summarizeBy: sum
				sourceColumn: NumberWaiting

				annotation SummarizationSetBy = Automatic

			column NumberWaitingQF
				dataType: string
				lineageTag: fb10967e-d41b-4ed8-bd6a-e4fbbaa43d17
				summarizeBy: none
				sourceColumn: NumberWaitingQF

				annotation SummarizationSetBy = Automatic

			column NumberOver12Weeks
				dataType: int64
				formatString: 0
				lineageTag: 0d10e6e9-81fc-4431-8f23-6354c8f1a34a
				summarizeBy: sum
				sourceColumn: NumberOver12Weeks

				annotation SummarizationSetBy = Automatic

			column NumberOver12WeeksQF
				dataType: string
				lineageTag: 98e9e0dd-eb8d-4819-8536-b3ec07dd3352
				summarizeBy: none
				sourceColumn: NumberOver12WeeksQF

				annotation SummarizationSetBy = Automatic

			column MedianDays
				dataType: double
				lineageTag: 9a9a9816-42fd-4858-ae82-a15044606e40
				summarizeBy: none
				sourceColumn: MedianDays

				annotation SummarizationSetBy = User

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column MedianDaysQF
				dataType: string
				lineageTag: d75359da-785e-462d-9034-2f7a46d8b374
				summarizeBy: none
				sourceColumn: MedianDaysQF

				annotation SummarizationSetBy = Automatic

			column P90Days
				dataType: double
				lineageTag: d081ff02-9df0-43e3-b4b4-b5feb37e6e6e
				summarizeBy: none
				sourceColumn: P90Days

				annotation SummarizationSetBy = User

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column P90DaysQF
				dataType: string
				lineageTag: 817350a4-af74-4959-9c51-d98d05fbe4e2
				summarizeBy: none
				sourceColumn: P90DaysQF

				annotation SummarizationSetBy = Automatic

			column PeriodEndDate
				dataType: dateTime
				isHidden
				formatString: Long Date
				lineageTag: c83c727f-6f45-4c5d-b0fc-24692d107ef9
				summarizeBy: none
				sourceColumn: PeriodEndDate

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			partition Fact_OngoingWaits = m
				mode: import
				source =
						let
						  Source = src_OngoingWaits,
						  QfColumns = List.Select(Table.ColumnNames(Source), each Text.EndsWith(_, "QF")),
						  ValueColumns = {"Specialty", "NumberWaiting", "NumberWaitingOver12Weeks", "Median", "90thPercentile"},
						  BlanksToNull = Table.ReplaceValue(Source, "", null, Replacer.ReplaceValue, ValueColumns & QfColumns),
						  AddedDate = Table.AddColumn(
						    BlanksToNull,
						    "PeriodEndDate",
						    each #date(
						      Number.From(Text.Start([MonthEnding], 4)),
						      Number.From(Text.Middle([MonthEnding], 4, 2)),
						      Number.From(Text.End([MonthEnding], 2))
						    ),
						    type date
						  ),
						  RemoveOldDate = Table.RemoveColumns(AddedDate, {"MonthEnding"}),
						  Typed = Table.TransformColumnTypes(
						  RemoveOldDate,
						    {
						      {"NumberWaiting", Int64.Type},
						      {"NumberWaitingOver12Weeks", Int64.Type},
						      {"Median", type number},
						      {"90thPercentile", type number}
						    }
						  ),
						  Renamed = Table.RenameColumns(
						  Typed,
						    {
						      {"HBT", "HealthBoardCode"},
						      {"Specialty", "SpecialtyCode"},
						      {"NumberWaitingOver12Weeks", "NumberOver12Weeks"},
						      {"NumberWaitingOver12WeeksQF", "NumberOver12WeeksQF"},
						      {"Median", "MedianDays"},
						      {"MedianQF", "MedianDaysQF"},
						      {"90thPercentile", "P90Days"},
						      {"90thPercentileQF", "P90DaysQF"}
						    }
						  ),
						  FillBlankSpecialty = Table.TransformColumns(#"Renamed", {{"SpecialtyCode", each if _ = null or Text.Trim(_) = "" then "UNSPEC" else _, type text}})
						in
						  FillBlankSpecialty

			annotation PBI_ResultType = Table

		table DateTableTemplate_a8fe071a-1e7f-4917-913b-0166a894585e
			isHidden
			isPrivate
			lineageTag: 5a238bdf-01f7-4716-8e7c-7878a3e99f10

			column Date
				dataType: dateTime
				isHidden
				formatString: General Date
				lineageTag: a8991227-8607-4f3b-8e18-3911744ada32
				dataCategory: PaddedDateTableDates
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = User

			column Year = YEAR([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 5306ad63-ca7d-4ba1-a6eb-b8b66c91db89
				dataCategory: Years
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Year

			column MonthNo = MONTH([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 6d8d1ec5-2a89-4f72-8883-a52cf1ab5f3f
				dataCategory: MonthOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = MonthNumber

			column Month = FORMAT([Date], "MMMM")
				dataType: string
				isHidden
				lineageTag: 6f52efcc-821f-442f-9475-238d7dbb4c05
				dataCategory: Months
				summarizeBy: none
				sortByColumn: MonthNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Month

			column QuarterNo = INT(([MonthNo] + 2) / 3)
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 99cab145-3739-468c-b36f-e43c350b6b9a
				dataCategory: QuarterOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = QuarterNumber

			column Quarter = "Qtr " & [QuarterNo]
				dataType: string
				isHidden
				lineageTag: 1b2d9536-b60c-4981-b759-a90efb3de412
				dataCategory: Quarters
				summarizeBy: none
				sortByColumn: QuarterNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Quarter

			column Day = DAY([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: bca1e6e3-311f-460d-8801-edb95c459293
				dataCategory: DayOfMonth
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Day

			hierarchy 'Date Hierarchy'
				lineageTag: 42a145d2-2966-4f80-a3a2-4756a2dafbbf

				level Year
					lineageTag: 17aa53e0-d057-40e3-8da5-025284876a6c
					column: Year

				level Quarter
					lineageTag: 80ee168e-34d0-434d-bb0a-352f13fdc0c8
					column: Quarter

				level Month
					lineageTag: 47ca947b-8cdd-4e04-821b-be3e0f94024d
					column: Month

				level Day
					lineageTag: 9fda9ddb-8485-4aca-ae6c-14d335aa9177
					column: Day

				annotation TemplateId = DateHierarchy

			partition DateTableTemplate_a8fe071a-1e7f-4917-913b-0166a894585e = calculated
				mode: import
				source = Calendar(Date(2015,1,1), Date(2015,1,1))

			annotation __PBI_TemplateDateTable = true

			annotation DefaultItem = DateHierarchy

		table Fact_CompletedWaits
			lineageTag: daef1665-92c1-4557-9e6e-cc38ff436ac5

			measure 'Patients Seen' =
					
					VAR LatestPeriod =
					    CALCULATE (
					        MAX ( Fact_CompletedWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR BoardSelected =
					    ISFILTERED ( Dim_HealthBoard[HealthBoardCode] )
					        || ISFILTERED ( Dim_HealthBoard[Board Name] )
					        || ISFILTERED ( Dim_HealthBoard[Board Type] )
					VAR SpecialtySelected =
					    ISFILTERED ( Dim_Specialty[SpecialtyCode] )
					        || ISFILTERED ( Dim_Specialty[Specialty Name] )
					VAR ScopeRows =
					    CALCULATETABLE (
					        Fact_CompletedWaits,
					        Fact_CompletedWaits[PeriodEndDate] = LatestPeriod,
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[HealthBoardCode] ),
					                IF (
					                    BoardSelected,
					                    Fact_CompletedWaits[HealthBoardCode] <> "S92000003",
					                    Fact_CompletedWaits[HealthBoardCode] = "S92000003"
					                )
					            )
					        ),
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[SpecialtyCode] ),
					                IF (
					                    SpecialtySelected,
					                    Fact_CompletedWaits[SpecialtyCode] <> "Z9",
					                    Fact_CompletedWaits[SpecialtyCode] = "Z9"
					                )
					            )
					        )
					    )
					VAR HasSuppressed =
					    NOT ISEMPTY ( FILTER ( ScopeRows, ISBLANK ( Fact_CompletedWaits[NumberSeen] ) ) )
					RETURN
					    IF ( NOT HasSuppressed, SUMX ( ScopeRows, Fact_CompletedWaits[NumberSeen] ) )
				formatString: 0
				lineageTag: 15529744-ceb2-478f-bd7d-180ba92ac6e2

			measure 'Median Wait (Days)' =
					
					VAR LatestPeriod =
					    CALCULATE (
					        MAX ( Fact_CompletedWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR BoardSelected =
					    ISFILTERED ( Dim_HealthBoard[HealthBoardCode] )
					        || ISFILTERED ( Dim_HealthBoard[Board Name] )
					        || ISFILTERED ( Dim_HealthBoard[Board Type] )
					VAR SpecialtySelected =
					    ISFILTERED ( Dim_Specialty[SpecialtyCode] )
					        || ISFILTERED ( Dim_Specialty[Specialty Name] )
					VAR ScopeRows =
					    CALCULATETABLE (
					        Fact_CompletedWaits,
					        Fact_CompletedWaits[PeriodEndDate] = LatestPeriod,
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[HealthBoardCode] ),
					                IF (
					                    BoardSelected,
					                    Fact_CompletedWaits[HealthBoardCode] <> "S92000003",
					                    Fact_CompletedWaits[HealthBoardCode] = "S92000003"
					                )
					            )
					        ),
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[SpecialtyCode] ),
					                IF (
					                    SpecialtySelected,
					                    Fact_CompletedWaits[SpecialtyCode] <> "Z9",
					                    Fact_CompletedWaits[SpecialtyCode] = "Z9"
					                )
					            )
					        )
					    )
					RETURN
					    IF (
					        COUNTROWS ( ScopeRows ) = 1,
					        MAXX ( ScopeRows, Fact_CompletedWaits[MedianDays] )
					    )
				formatString: 0
				lineageTag: a46c9310-05f4-44eb-b17b-aaac27704051

			measure 'Median Wait (Days) (Scotland)' =
					
					CALCULATE (
					    [Median Wait (Days)],
					    REMOVEFILTERS ( Dim_HealthBoard )
					)
				displayFolder: Benchmark
				lineageTag: f06c2033-3ca5-4382-ac1f-0d48c0a2de4d

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Median Wait vs Scotland (Days)' =
					
					VAR BoardValue = [Median Wait (Days)]
					VAR ScotlandValue = [Median Wait (Days) (Scotland)]
					RETURN
					    IF (
					        NOT ISBLANK ( BoardValue ) && NOT ISBLANK ( ScotlandValue ),
					        BoardValue - ScotlandValue
					    )
				formatString: " +0;-0;0"
				displayFolder: Benchmark
				lineageTag: 9495f285-3348-48c5-87af-2fd0eab9b1c7

				annotation PBI_FormatHint = {"isCustom":true}

			measure 'P90 Wait (Days)' =
					
					VAR LatestPeriod =
					    CALCULATE (
					        MAX ( Fact_CompletedWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR BoardSelected =
					    ISFILTERED ( Dim_HealthBoard[HealthBoardCode] )
					        || ISFILTERED ( Dim_HealthBoard[Board Name] )
					        || ISFILTERED ( Dim_HealthBoard[Board Type] )
					VAR SpecialtySelected =
					    ISFILTERED ( Dim_Specialty[SpecialtyCode] )
					        || ISFILTERED ( Dim_Specialty[Specialty Name] )
					VAR ScopeRows =
					    CALCULATETABLE (
					        Fact_CompletedWaits,
					        Fact_CompletedWaits[PeriodEndDate] = LatestPeriod,
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[HealthBoardCode] ),
					                IF (
					                    BoardSelected,
					                    Fact_CompletedWaits[HealthBoardCode] <> "S92000003",
					                    Fact_CompletedWaits[HealthBoardCode] = "S92000003"
					                )
					            )
					        ),
					        KEEPFILTERS (
					            FILTER (
					                ALL ( Fact_CompletedWaits[SpecialtyCode] ),
					                IF (
					                    SpecialtySelected,
					                    Fact_CompletedWaits[SpecialtyCode] <> "Z9",
					                    Fact_CompletedWaits[SpecialtyCode] = "Z9"
					                )
					            )
					        )
					    )
					RETURN
					    IF (
					        COUNTROWS ( ScopeRows ) = 1,
					        MAXX ( ScopeRows, Fact_CompletedWaits[P90Days] )
					    )
				formatString: 0
				lineageTag: 20041b51-50ff-459d-9a28-a37a76b118b0

			measure 'Quarters to Clear List' =
					
					VAR SeenPeriod =
					    CALCULATE (
					        MAX ( Fact_CompletedWaits[PeriodEndDate] ),
					        REMOVEFILTERS ( Dim_HealthBoard ),
					        REMOVEFILTERS ( Dim_PatientType ),
					        REMOVEFILTERS ( Dim_Specialty )
					    )
					VAR Waiting =
					    CALCULATE ( [Patients Waiting], Dim_Period[PeriodEndDate] = SeenPeriod )
					VAR Seen =
					    CALCULATE ( [Patients Seen], Dim_Period[PeriodEndDate] = SeenPeriod )
					RETURN
					    IF (
					        HASONEVALUE ( Dim_PatientType[PatientType] )
					            && NOT ISBLANK ( SeenPeriod )
					            && NOT ISBLANK ( Waiting )
					            && Seen > 0,
					        DIVIDE ( Waiting, Seen )
					    )
				formatString: 0.0
				lineageTag: dc74a38b-b998-46d9-b098-a5e9b21cf943

			measure 'Quarters to Clear List (Scotland)' =
					
					CALCULATE ( [Quarters to Clear List], REMOVEFILTERS ( Dim_HealthBoard ) )
				isHidden
				displayFolder: Benchmark
				lineageTag: 25142192-34b0-4900-97ae-c0d8cf8c5f6f

				changedProperty = IsHidden

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			measure 'Quarters to Clear vs Scotland' =
					
					[Quarters to Clear List] - [Quarters to Clear List (Scotland)]
				formatString: +0.0;-0.0;0.0
				displayFolder: Benchmark
				lineageTag: 115b5b75-f543-4c4f-abd6-6f7f28f6d413

				annotation PBI_FormatHint = {"isCustom":true}

			column HealthBoardCode
				dataType: string
				isHidden
				lineageTag: 8591c034-a526-48f5-b3a3-7e813767cf19
				summarizeBy: none
				sourceColumn: HealthBoardCode

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column HBTQF
				dataType: string
				lineageTag: babbde84-4649-4961-bda4-681c625eff79
				summarizeBy: none
				sourceColumn: HBTQF

				annotation SummarizationSetBy = Automatic

			column PatientType
				dataType: string
				isHidden
				lineageTag: 5bfdf7ba-2bbd-42b8-9549-24225b0e55bd
				summarizeBy: none
				sourceColumn: PatientType

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SpecialtyCode
				dataType: string
				isHidden
				lineageTag: d211cfac-2648-432f-9c0e-685efc90cb9e
				summarizeBy: none
				sourceColumn: SpecialtyCode

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SpecialtyQF
				dataType: string
				lineageTag: aee7f0cc-70aa-44b1-bc9d-dc688039e308
				summarizeBy: none
				sourceColumn: SpecialtyQF

				annotation SummarizationSetBy = Automatic

			column NumberSeen
				dataType: int64
				formatString: 0
				lineageTag: 7879971a-02df-4bc4-be9e-4a258a90e705
				summarizeBy: sum
				sourceColumn: NumberSeen

				annotation SummarizationSetBy = Automatic

			column NumberSeenQF
				dataType: string
				lineageTag: 792fe22f-36df-4dbe-bd96-f0de93ad81b7
				summarizeBy: none
				sourceColumn: NumberSeenQF

				annotation SummarizationSetBy = Automatic

			column NumberOver12Weeks
				dataType: int64
				formatString: 0
				lineageTag: 6b9fbadc-0424-4a9d-a50a-a3677fd855bb
				summarizeBy: sum
				sourceColumn: NumberOver12Weeks

				annotation SummarizationSetBy = Automatic

			column NumberOver12WeeksQF
				dataType: string
				lineageTag: 67ac7e4c-eaaf-44bb-8500-d1b2eca6690c
				summarizeBy: none
				sourceColumn: NumberOver12WeeksQF

				annotation SummarizationSetBy = Automatic

			column MedianDays
				dataType: double
				lineageTag: 7d6f3ec6-52e6-4f72-bda1-235125681cef
				summarizeBy: none
				sourceColumn: MedianDays

				annotation SummarizationSetBy = User

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column MedianDaysQF
				dataType: string
				lineageTag: 83c3eeef-aad0-4068-821a-f3c0b1f82af7
				summarizeBy: none
				sourceColumn: MedianDaysQF

				annotation SummarizationSetBy = Automatic

			column P90Days
				dataType: double
				lineageTag: 4b6e3fc3-f15d-43dd-941b-9decb29f4b68
				summarizeBy: none
				sourceColumn: P90Days

				annotation SummarizationSetBy = User

				annotation PBI_FormatHint = {"isGeneralNumber":true}

			column P90DaysQF
				dataType: string
				lineageTag: f53d3e62-6525-40c3-ab27-154ab366744d
				summarizeBy: none
				sourceColumn: P90DaysQF

				annotation SummarizationSetBy = Automatic

			column PeriodEndDate
				dataType: dateTime
				isHidden
				formatString: Long Date
				lineageTag: 3cfa4fa0-3c05-414a-aa3c-e991f9bf7f4d
				summarizeBy: none
				sourceColumn: PeriodEndDate

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			partition Fact_CompletedWaits = m
				mode: import
				source =
						let
						  Source = src_CompletedWaits,
						  QfColumns = List.Select(Table.ColumnNames(Source), each Text.EndsWith(_, "QF")),
						  ValueColumns = {"Specialty", "NumberSeen", "WaitedOver12Weeks", "Median", "90thPercentile"},
						  BlanksToNull = Table.ReplaceValue(Source, "", null, Replacer.ReplaceValue, ValueColumns & QfColumns),
						  AddedDate = Table.AddColumn(
						    BlanksToNull,
						    "PeriodEndDate",
						    each #date(
						      Number.From(Text.Start([QuarterEnding], 4)),
						      Number.From(Text.Middle([QuarterEnding], 4, 2)),
						      Number.From(Text.End([QuarterEnding], 2))
						    ),
						    type date
						  ),
						  RemoveOldDate = Table.RemoveColumns(AddedDate, {"QuarterEnding"}),
						  Typed = Table.TransformColumnTypes(
						    RemoveOldDate,
						    {
						      {"NumberSeen", Int64.Type},
						      {"WaitedOver12Weeks", Int64.Type},
						      {"Median", type number},
						      {"90thPercentile", type number}
						    }
						  ),
						  Renamed = Table.RenameColumns(
						    Typed,
						    {
						      {"HBT", "HealthBoardCode"},
						      {"Specialty", "SpecialtyCode"},
						      {"WaitedOver12Weeks", "NumberOver12Weeks"},
						      {"WaitedOver12WeeksQF", "NumberOver12WeeksQF"},
						      {"Median", "MedianDays"},
						      {"MedianQF", "MedianDaysQF"},
						      {"90thPercentile", "P90Days"},
						      {"90thPercentileQF", "P90DaysQF"}
						    }
						  ),
						  FillBlankSpecialty = Table.TransformColumns(#"Renamed", {{"SpecialtyCode", each if _ = null or Text.Trim(_) = "" then "UNSPEC" else _, type text}})
						in
						  FillBlankSpecialty

			annotation PBI_ResultType = Table

		table Dim_Period
			lineageTag: 9abea536-e223-4847-8596-f2ce60704068

			column PeriodEndDate
				formatString: General Date
				lineageTag: 93ef1b5b-4795-4949-885d-87697ab04308
				summarizeBy: none
				isNameInferred
				sourceColumn: Fact_OngoingWaits[PeriodEndDate]

				variation Variation
					isDefault
					relationship: dcc085d3-db20-4368-a693-80cb4d1ee6a0
					defaultHierarchy: LocalDateTable_5410980f-8621-415e-abec-49877a8bd68e.'Date Hierarchy'

				annotation SummarizationSetBy = Automatic

			column Year
				formatString: 0
				lineageTag: 57c0ead9-745c-4e43-90cc-4b9be591b005
				summarizeBy: none
				isNameInferred
				sourceColumn: [Year]

				annotation SummarizationSetBy = User

			column 'Month Label'
				lineageTag: 9d3560e3-90eb-457c-8a74-e7e640440048
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month Label]
				sortByColumn: 'Month Sort'

				annotation SummarizationSetBy = Automatic

			column 'Month Sort'
				formatString: 0
				lineageTag: 78c6ecb0-5764-43b1-8681-f1fd2fa92a11
				summarizeBy: none
				isNameInferred
				sourceColumn: [Month Sort]

				annotation SummarizationSetBy = User

			partition Dim_Period = calculated
				mode: import
				source =
						
						VAR Periods =
						    DISTINCT (
						        UNION (
						            DISTINCT ( Fact_OngoingWaits[PeriodEndDate] ),
						            DISTINCT ( Fact_CompletedWaits[PeriodEndDate] )
						        )
						    )
						RETURN
						    ADDCOLUMNS (
						        Periods,
						        "Year", YEAR ( [PeriodEndDate] ),
						        "Month Label", FORMAT ( [PeriodEndDate], "mmm yyyy" ),
						        "Month Sort", YEAR ( [PeriodEndDate] ) * 100 + MONTH ( [PeriodEndDate] )
						    )

			annotation PBI_Id = e04d664e8ede45368d35238bbd1f24d6

		table LocalDateTable_5410980f-8621-415e-abec-49877a8bd68e
			isHidden
			showAsVariationsOnly
			lineageTag: d3196112-ea79-4c4c-b406-b3d05af31272

			column Date
				dataType: dateTime
				isHidden
				formatString: General Date
				lineageTag: a11fed26-68bb-4403-9623-d817ce3807f3
				dataCategory: PaddedDateTableDates
				summarizeBy: none
				isNameInferred
				sourceColumn: [Date]

				annotation SummarizationSetBy = User

			column Year = YEAR([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 40baae38-f702-4547-92d4-e48a66e23ae9
				dataCategory: Years
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Year

			column MonthNo = MONTH([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 906638c2-1245-42a7-bacb-2a143ba4b6ea
				dataCategory: MonthOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = MonthNumber

			column Month = FORMAT([Date], "MMMM")
				dataType: string
				isHidden
				lineageTag: 8d5a1ecb-d6d7-4a68-9aa3-4e29b6ea2e00
				dataCategory: Months
				summarizeBy: none
				sortByColumn: MonthNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Month

			column QuarterNo = INT(([MonthNo] + 2) / 3)
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: d29c6d83-0af3-481d-a4d3-e305eb0be658
				dataCategory: QuarterOfYear
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = QuarterNumber

			column Quarter = "Qtr " & [QuarterNo]
				dataType: string
				isHidden
				lineageTag: 6d75e338-bfb1-4f5d-9f7f-9e6dd64a96cb
				dataCategory: Quarters
				summarizeBy: none
				sortByColumn: QuarterNo

				annotation SummarizationSetBy = User

				annotation TemplateId = Quarter

			column Day = DAY([Date])
				dataType: int64
				isHidden
				formatString: 0
				lineageTag: 857bda7b-dc35-4ba1-b601-07a4b92d8285
				dataCategory: DayOfMonth
				summarizeBy: none

				annotation SummarizationSetBy = User

				annotation TemplateId = Day

			hierarchy 'Date Hierarchy'
				lineageTag: 9704934b-494a-489d-8bf1-0b803ead1909

				level Year
					lineageTag: d1f34595-b54e-460b-b4e7-51dcd59cb662
					column: Year

				level Quarter
					lineageTag: 81e57716-d719-4a65-9c21-f3a74930abca
					column: Quarter

				level Month
					lineageTag: 0a88f9e8-85ed-40e9-b309-1ad3f6c31d01
					column: Month

				level Day
					lineageTag: 4328532b-893d-40ff-8308-da0ee5551a73
					column: Day

				annotation TemplateId = DateHierarchy

			partition LocalDateTable_5410980f-8621-415e-abec-49877a8bd68e = calculated
				mode: import
				source = Calendar(Date(Year(MIN('Dim_Period'[PeriodEndDate])), 1, 1), Date(Year(MAX('Dim_Period'[PeriodEndDate])), 12, 31))

			annotation __PBI_LocalDateTable = true

		table Dim_PatientType
			lineageTag: 25669e7a-69f4-44b0-a5ec-75d882279822

			column PatientType
				lineageTag: 354a7b1d-1975-4045-bdbf-41b3d6e80af7
				summarizeBy: none
				isNameInferred
				sourceColumn: Fact_OngoingWaits[PatientType]

				annotation SummarizationSetBy = Automatic

			partition Dim_PatientType = calculated
				mode: import
				source =
						
						DISTINCT (
						    UNION (
						        DISTINCT ( Fact_OngoingWaits[PatientType] ),
						        DISTINCT ( Fact_CompletedWaits[PatientType] )
						    )
						)

			annotation PBI_Id = f00edf193f03413d8afc08df04f12c2f

		table Dim_HealthBoard
			lineageTag: cdfaab2f-113b-418a-a9d3-f87cc37c6295

			column HealthBoardCode
				lineageTag: d34e1199-784c-43a8-9ccf-330ed90704e4
				summarizeBy: none
				isNameInferred
				sourceColumn: Fact_OngoingWaits[HealthBoardCode]

				annotation SummarizationSetBy = Automatic

			column 'Board Name' =
					
					VAR _code = Dim_HealthBoard[HealthBoardCode]
					RETURN
					    SWITCH (
					        TRUE (),
					        _code = "S92000003", "Scotland",
					        COALESCE (
					            LOOKUPVALUE ( Ref_HealthBoard[HBName], Ref_HealthBoard[HB], _code ),
					            _code
					        )
					    )
				lineageTag: dbcb7af2-c887-4ad1-b9be-a96081d24e0f
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			column 'Board Type' =
					
					VAR _code = Dim_HealthBoard[HealthBoardCode]
					RETURN
					    SWITCH (
					        TRUE (),
					        _code = "S92000003", "Scotland",
					        LEFT ( _code, 3 ) = "S08", "Regional",
					        LEFT ( _code, 2 ) = "SB", "Special",
					        "Other"
					    )
				lineageTag: 1da9dbe9-d882-4b07-947c-98a93aa03a15
				summarizeBy: none

				annotation SummarizationSetBy = Automatic

			partition Dim_HealthBoard = calculated
				mode: import
				source =
						
						DISTINCT (
						    UNION (
						        DISTINCT ( Fact_OngoingWaits[HealthBoardCode] ),
						        DISTINCT ( Fact_CompletedWaits[HealthBoardCode] )
						    )
						)

			annotation PBI_Id = d742d7cbf9914b2eb58e15856f44a939

		table Ref_HealthBoard
			isHidden
			lineageTag: f9c70fe6-6292-49fb-b9bf-5b3b0968425f

			column HB
				dataType: string
				isHidden
				lineageTag: 62275ac5-6a24-46e6-a77f-bf4d357eec4a
				summarizeBy: none
				sourceColumn: HB

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column HBName
				dataType: string
				isHidden
				lineageTag: 6dd53801-f67a-44ec-bc8d-67375db7ea0e
				summarizeBy: none
				sourceColumn: HBName

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			partition Ref_HealthBoard = m
				mode: import
				source =
						let
						  Source = fnLoadBronzeTable("health_board_lookup"),
						  #"Changed column type" = Table.TransformColumnTypes(Source, {{"HB", type text}, {"HBName", type text}, {"HBDateEnacted", Int64.Type}, {"HBDateArchived", Int64.Type}, {"Country", type text}}, "en-GB"),
						  #"Filtered rows" = Table.SelectRows(#"Changed column type", each ([HBDateArchived] = null)),
						  #"Removed other columns" = Table.SelectColumns(#"Filtered rows", {"HB", "HBName"}),
						  Combined = Table.Combine({
						    #"Removed other columns",
						    src_SpecialHealthBoards,
						    src_IsdHealthBoardOfTreatment,
						    src_OtherResidentialCategories
						  })
						in
						  Combined

			changedProperty = IsHidden

			annotation PBI_ResultType = Table

		table Ref_Specialty
			isHidden
			lineageTag: ba75af20-cfe3-4194-850b-157fb5a5af2b

			column SpecialtyCode
				dataType: string
				isHidden
				lineageTag: 6a0f86b3-ef69-40f7-a1c8-52f63cc819cd
				summarizeBy: none
				sourceColumn: SpecialtyCode

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			column SpecialtyName
				dataType: string
				isHidden
				lineageTag: 53fb1cd0-f729-48f0-9de4-5c0276619f1a
				summarizeBy: none
				sourceColumn: SpecialtyName

				changedProperty = IsHidden

				annotation SummarizationSetBy = Automatic

			partition Ref_Specialty = m
				mode: import
				source =
						let
						    Source = src_Specialty,
						    Kept = Table.SelectColumns(Source, {"Specialty", "SpecialtyName"}),
						    Renamed = Table.RenameColumns(Kept, {{"Specialty", "SpecialtyCode"}}),
						    Typed = Table.TransformColumnTypes(Renamed, {
						        {"SpecialtyCode", type text},
						        {"SpecialtyName", type text}
						    }),
						    Cleaned = Table.TransformColumns(Typed, {
						        {"SpecialtyCode", Text.Trim, type text},
						        {"SpecialtyName", each Text.Trim(Text.Replace(_, Character.FromNumber(65533), " ")), type text}
						    }),
						    NoZ9 = Table.SelectRows(Cleaned, each [SpecialtyCode] <> "Z9"),
						    AddAll = Table.Combine({
						        NoZ9,
						        #table(type table [SpecialtyCode = text, SpecialtyName = text], {
						            {"Z9", "All Specialties"},
						            {"UNSPEC", "Unspecified / unlisted"}
						        })
						    }),
						    Deduped = Table.Distinct(AddAll, {"SpecialtyCode"})
						in
						    Deduped

			changedProperty = IsHidden

			annotation PBI_ResultType = Table

		table Dim_Specialty
			lineageTag: 300be147-6e47-45d2-b9ad-74599fa196ab

			column SpecialtyCode
				lineageTag: 050ac822-8966-4397-9538-80a49d4b8974
				summarizeBy: none
				isNameInferred
				sourceColumn: Fact_OngoingWaits[SpecialtyCode]

				annotation SummarizationSetBy = Automatic

			column 'Specialty Name'
				lineageTag: 74684500-1041-4558-86d3-ce62f7a1a8f1
				summarizeBy: none
				isNameInferred
				sourceColumn: [Specialty Name]

				annotation SummarizationSetBy = Automatic

			column 'Is All Specialties'
				formatString: """TRUE"";""TRUE"";""FALSE"""
				lineageTag: fd0899f1-e59d-4c46-b803-5e1682b3e55e
				summarizeBy: none
				isNameInferred
				sourceColumn: [Is All Specialties]

				annotation SummarizationSetBy = Automatic

			partition Dim_Specialty = calculated
				mode: import
				source =
						
						VAR Codes =
						    FILTER (
						        DISTINCT (
						            UNION (
						                DISTINCT ( Fact_OngoingWaits[SpecialtyCode] ),
						                DISTINCT ( Fact_CompletedWaits[SpecialtyCode] )
						            )
						        ),
						        NOT ISBLANK ( [SpecialtyCode] ) && TRIM ( [SpecialtyCode] ) <> ""
						    )
						RETURN
						    ADDCOLUMNS (
						        Codes,
						        "Specialty Name",
						            COALESCE (
						                LOOKUPVALUE ( Ref_Specialty[SpecialtyName], Ref_Specialty[SpecialtyCode], [SpecialtyCode] ),
						                [SpecialtyCode]
						            ),
						        "Is All Specialties", [SpecialtyCode] = "Z9"
						    )

			annotation PBI_Id = 6a7684ff3ee34659a9e07211bdddc412

		relationship dcc085d3-db20-4368-a693-80cb4d1ee6a0
			joinOnDateBehavior: datePartOnly
			fromColumn: Dim_Period.PeriodEndDate
			toColumn: LocalDateTable_5410980f-8621-415e-abec-49877a8bd68e.Date

		relationship 42b8233f-66e9-8a5f-143b-17922fbabdde
			fromColumn: Fact_OngoingWaits.PeriodEndDate
			toColumn: Dim_Period.PeriodEndDate

		relationship 88cd8dcf-2587-fe99-03ba-25405cad99d7
			fromColumn: Fact_CompletedWaits.PeriodEndDate
			toColumn: Dim_Period.PeriodEndDate

		relationship 3687b8a1-56fa-2b30-e756-aac0760e8795
			fromColumn: Fact_OngoingWaits.PatientType
			toColumn: Dim_PatientType.PatientType

		relationship 9e6392e9-566f-7160-f852-d9b815a81463
			fromColumn: Fact_CompletedWaits.PatientType
			toColumn: Dim_PatientType.PatientType

		relationship 800ebbdf-d823-9ada-a397-8f1734054cf6
			fromColumn: Fact_OngoingWaits.HealthBoardCode
			toColumn: Dim_HealthBoard.HealthBoardCode

		relationship 87566bd3-ba48-3a24-97ca-5c4f210b536d
			fromColumn: Fact_CompletedWaits.HealthBoardCode
			toColumn: Dim_HealthBoard.HealthBoardCode

		relationship e050d9b8-16b5-435d-ca4d-387cf9d25fc3
			fromColumn: Fact_OngoingWaits.SpecialtyCode
			toColumn: Dim_Specialty.SpecialtyCode

		relationship 120c3f75-4911-7e6e-c511-dd8d3b1e2556
			fromColumn: Fact_CompletedWaits.SpecialtyCode
			toColumn: Dim_Specialty.SpecialtyCode

		expression fnLoadBronzeTable =
				(TableName as text) as table =>
				let
				    Source = Csv.Document(
				        Web.Contents(
				            "https://raw.githubusercontent.com",
				            [RelativePath = GitHubRepoPath & "/data/bronze/" & TableName & "/" & TableName & ".csv"]
				        ),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true])
				in
				    PromotedHeaders
			lineageTag: 3c566989-0c36-4140-bb48-abb2b01f8139

			annotation PBI_ResultType = Function

		expression src_OngoingWaits =
				let
				  Source = fnLoadBronzeTable("ongoing_waits")
				in
				  Source
			lineageTag: c4ea1aae-2623-45dc-a7e6-7b52a6305d18

			annotation PBI_ResultType = Table

		expression src_CompletedWaits =
				let
				    Source = fnLoadBronzeTable("completed_waits")
				in
				    Source
			lineageTag: f7789dc2-6be5-4e4c-8113-e738ed145e4e

			annotation PBI_ResultType = Table

		expression ResourceId_OngoingWaits = "5816ec92-66bf-4033-ae55-9df45ff19d49" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: 1fab1681-d8d4-44c2-aaae-bb85b143916d

			annotation PBI_ResultType = Text

		expression ResourceId_CompletedWaits = "4c091d26-1492-41e5-9577-832cbc1cd4cf" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: e3721615-2d7b-4928-b3e7-596187807b8d

			annotation PBI_ResultType = Text

		expression ResourceId_HealthBoardLabels = "652ff726-e676-4a20-abda-435b98dd7bdc" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: b77ff747-30c6-48dd-aa6d-2bcdcb1665ab

			annotation PBI_ResultType = Text

		expression ResourceId_CountryLabels = "9c6e6c56-2697-4184-92c6-60d69c2b6792" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: b069a788-e894-4e09-a885-e21740493d6f

			annotation PBI_ResultType = Text

		expression ResourceId_SpecialHealthBoardLabels = "0450a5a2-f600-4569-a9ae-5d6317141899" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: 495fe319-e410-41fb-a43e-89b5c8aaf14d

			annotation PBI_ResultType = Text

		expression ResourceId_SpecialtyLabels = "6f2e3da0-b1b5-46cc-ac04-78495daedfa3" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: f45ea326-978a-44ab-9bfb-47dd37158baf

			annotation PBI_ResultType = Text

		expression GitHubRepoPath = "EmmaSwan0729/scottish-nhs-performance-bi/main" meta [IsParameterQuery = true, Type = "Text", IsParameterQueryRequired = true]
			lineageTag: 746bda33-c182-4d9b-ad70-6d61e05cb989

			annotation PBI_ResultType = Text

		expression src_SpecialHealthBoards =
				let
				  Source = fnLoadBronzeTable("special_health_boards"),
				  CleanedName = Table.TransformColumns(
				    Source,
				    {{"SHBName", each Text.Trim(Text.Replace(_, Character.FromNumber(65533), " ")), type text}}
				  ),
				  KeptColumns = Table.SelectColumns(CleanedName, {"SHB", "SHBName"}),
				  Renamed = Table.RenameColumns(KeptColumns, {{"SHB", "HB"}, {"SHBName", "HBName"}}),
				  Typed = Table.TransformColumnTypes(Renamed, {{"HB", type text}})
				in
				  Typed
			lineageTag: bbad5235-d927-4a32-aac7-80a94794ee1f

			annotation PBI_ResultType = Table

		expression src_IsdHealthBoardOfTreatment =
				let
				  Source = fnLoadBronzeTable("isd_health_board_of_treatment"),
				  KeptColumns = Table.SelectColumns(Source, {"ISDHBT", "ISDHBTName"}),
				  Renamed = Table.RenameColumns(KeptColumns, {{"ISDHBT", "HB"}, {"ISDHBTName", "HBName"}}),
				  Typed = Table.TransformColumnTypes(Renamed, {{"HB", type text}, {"HBName", type text}})
				in
				  Typed
			lineageTag: cdb3aaf0-1ebb-4e6c-8560-5abb6ffb63e5

			annotation PBI_ResultType = Table

		expression src_OtherResidentialCategories =
				let
				  Source = fnLoadBronzeTable("other_residential_categories"),
				  KeptColumns = Table.SelectColumns(Source, {"CustomResidency", "CustomResidencyName"}),
				  Renamed = Table.RenameColumns(KeptColumns, {{"CustomResidency", "HB"}, {"CustomResidencyName", "HBName"}}),
				  Typed = Table.TransformColumnTypes(Renamed, {{"HB", type text}, {"HBName", type text}})
				in
				  Typed
			lineageTag: 411db97e-b073-4850-9aa6-e0f7c01dae6c

			annotation PBI_ResultType = Table

		expression src_Specialty =
				let
				  Source = fnLoadBronzeTable("specialty")
				in
				  Source
			lineageTag: 636bb6af-948b-4ed7-a361-7f2e02bbc5b2

			annotation PBI_ResultType = Table

		annotation __PBI_TimeIntelligenceEnabled = 1

		annotation PBI_QueryOrder = ["ResourceId_OngoingWaits","ResourceId_CompletedWaits","ResourceId_HealthBoardLabels","ResourceId_CountryLabels","ResourceId_SpecialHealthBoardLabels","ResourceId_SpecialtyLabels","fnLoadBronzeTable","src_OngoingWaits","GitHubRepoPath","src_CompletedWaits","Fact_OngoingWaits","Fact_CompletedWaits","Ref_HealthBoard","src_SpecialHealthBoards","src_IsdHealthBoardOfTreatment","src_OtherResidentialCategories","src_Specialty","Ref_Specialty"]

		annotation __LastRPTime = 134354542015824081

		annotation PBI_ProTooling = ["WebModelingEdit","DaxQueryView_Desktop","TMDLView_Desktop"]

